# Generated by Django 4.2.5 on 2023-10-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%Y/%m/%d"),
        ),
    ]
